# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ndust.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 838)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 726))
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 791))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.Grid = QtWidgets.QWidget()
        self.Grid.setObjectName("Grid")
        self.groupBox_volumes = QtWidgets.QGroupBox(self.Grid)
        self.groupBox_volumes.setGeometry(QtCore.QRect(10, 170, 380, 431))
        self.groupBox_volumes.setObjectName("groupBox_volumes")
        self.line_4 = QtWidgets.QFrame(self.groupBox_volumes)
        self.line_4.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_volumes)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 361, 381))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_maxrad = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_maxrad.setToolTipDuration(-1)
        self.lineEdit_maxrad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxrad.setReadOnly(True)
        self.lineEdit_maxrad.setObjectName("lineEdit_maxrad")
        self.gridLayout.addWidget(self.lineEdit_maxrad, 5, 2, 1, 1)
        self.lineEdit_minvol = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_minvol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_minvol.setReadOnly(True)
        self.lineEdit_minvol.setObjectName("lineEdit_minvol")
        self.gridLayout.addWidget(self.lineEdit_minvol, 4, 2, 1, 1)
        self.label_numvsecs = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_numvsecs.setObjectName("label_numvsecs")
        self.gridLayout.addWidget(self.label_numvsecs, 8, 0, 1, 1)
        self.label_base = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_base.setObjectName("label_base")
        self.gridLayout.addWidget(self.label_base, 9, 0, 1, 1)
        self.spinBox_vsecs = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox_vsecs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_vsecs.setMinimum(20)
        self.spinBox_vsecs.setMaximum(250)
        self.spinBox_vsecs.setSingleStep(2)
        self.spinBox_vsecs.setProperty("value", 30)
        self.spinBox_vsecs.setObjectName("spinBox_vsecs")
        self.gridLayout.addWidget(self.spinBox_vsecs, 8, 2, 1, 1)
        self.label_maxrad = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_maxrad.setObjectName("label_maxrad")
        self.gridLayout.addWidget(self.label_maxrad, 5, 0, 1, 1)
        self.lineEdit_maxvol = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_maxvol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_maxvol.setReadOnly(True)
        self.lineEdit_maxvol.setObjectName("lineEdit_maxvol")
        self.gridLayout.addWidget(self.lineEdit_maxvol, 6, 2, 1, 1)
        self.label_minvol = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_minvol.setObjectName("label_minvol")
        self.gridLayout.addWidget(self.label_minvol, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.lineEdit_base = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_base.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_base.setObjectName("lineEdit_base")
        self.gridLayout.addWidget(self.lineEdit_base, 9, 2, 1, 1)
        self.label_maxvol = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_maxvol.setObjectName("label_maxvol")
        self.gridLayout.addWidget(self.label_maxvol, 6, 0, 1, 1)
        self.label_power = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_power.setObjectName("label_power")
        self.gridLayout.addWidget(self.label_power, 10, 0, 1, 1)
        self.lineEdit_minrad = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_minrad.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_minrad.setObjectName("lineEdit_minrad")
        self.gridLayout.addWidget(self.lineEdit_minrad, 3, 2, 1, 1)
        self.lineEdit_power = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_power.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_power.setObjectName("lineEdit_power")
        self.gridLayout.addWidget(self.lineEdit_power, 10, 2, 1, 1)
        self.label_minrad = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_minrad.setObjectName("label_minrad")
        self.gridLayout.addWidget(self.label_minrad, 3, 0, 1, 1)
        self.label_linear = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_linear.setObjectName("label_linear")
        self.gridLayout.addWidget(self.label_linear, 7, 0, 1, 1)
        self.checkBox_linear = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_linear.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_linear.setText("")
        self.checkBox_linear.setChecked(False)
        self.checkBox_linear.setObjectName("checkBox_linear")
        self.gridLayout.addWidget(self.checkBox_linear, 7, 2, 1, 1)
        self.label_special = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_special.setObjectName("label_special")
        self.gridLayout.addWidget(self.label_special, 0, 0, 1, 1)
        self.checkBox_special = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_special.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_special.setText("")
        self.checkBox_special.setChecked(False)
        self.checkBox_special.setObjectName("checkBox_special")
        self.gridLayout.addWidget(self.checkBox_special, 0, 2, 1, 1)
        self.label_special_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_special_2.setObjectName("label_special_2")
        self.gridLayout.addWidget(self.label_special_2, 1, 0, 1, 1)
        self.label_special_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_special_3.setObjectName("label_special_3")
        self.gridLayout.addWidget(self.label_special_3, 2, 0, 1, 1)
        self.checkBox_small = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_small.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_small.setText("")
        self.checkBox_small.setChecked(False)
        self.checkBox_small.setObjectName("checkBox_small")
        self.gridLayout.addWidget(self.checkBox_small, 1, 2, 1, 1)
        self.checkBox_big = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_big.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_big.setText("")
        self.checkBox_big.setChecked(False)
        self.checkBox_big.setObjectName("checkBox_big")
        self.gridLayout.addWidget(self.checkBox_big, 2, 2, 1, 1)
        self.groupBox_charges = QtWidgets.QGroupBox(self.Grid)
        self.groupBox_charges.setEnabled(True)
        self.groupBox_charges.setGeometry(QtCore.QRect(400, 10, 380, 220))
        self.groupBox_charges.setObjectName("groupBox_charges")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_charges)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 361, 171))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_maxneg = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_maxneg.setObjectName("label_maxneg")
        self.gridLayout_5.addWidget(self.label_maxneg, 0, 0, 1, 1)
        self.label_maxpos = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_maxpos.setObjectName("label_maxpos")
        self.gridLayout_5.addWidget(self.label_maxpos, 1, 0, 1, 1)
        self.label_qsecs = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_qsecs.setObjectName("label_qsecs")
        self.gridLayout_5.addWidget(self.label_qsecs, 2, 0, 1, 1)
        self.lineEdit_qsecs = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_qsecs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_qsecs.setReadOnly(True)
        self.lineEdit_qsecs.setObjectName("lineEdit_qsecs")
        self.gridLayout_5.addWidget(self.lineEdit_qsecs, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 1, 1, 1, 1)
        self.spinBox_maxneg = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_maxneg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_maxneg.setMinimum(10)
        self.spinBox_maxneg.setMaximum(500)
        self.spinBox_maxneg.setSingleStep(2)
        self.spinBox_maxneg.setProperty("value", 30)
        self.spinBox_maxneg.setObjectName("spinBox_maxneg")
        self.gridLayout_5.addWidget(self.spinBox_maxneg, 0, 2, 1, 1)
        self.spinBox_maxpos = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.spinBox_maxpos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_maxpos.setMinimum(1)
        self.spinBox_maxpos.setMaximum(50)
        self.spinBox_maxpos.setSingleStep(1)
        self.spinBox_maxpos.setProperty("value", 5)
        self.spinBox_maxpos.setObjectName("spinBox_maxpos")
        self.gridLayout_5.addWidget(self.spinBox_maxpos, 1, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_charges)
        self.line.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_grid_save = QtWidgets.QGroupBox(self.Grid)
        self.groupBox_grid_save.setEnabled(True)
        self.groupBox_grid_save.setGeometry(QtCore.QRect(400, 600, 380, 151))
        self.groupBox_grid_save.setObjectName("groupBox_grid_save")
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_grid_save)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_grid_save_name = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_grid_save_name.setObjectName("label_grid_save_name")
        self.gridLayout_17.addWidget(self.label_grid_save_name, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem2, 0, 2, 1, 1)
        self.lineEdit_grid_save_name = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_grid_save_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_grid_save_name.setObjectName("lineEdit_grid_save_name")
        self.gridLayout_17.addWidget(self.lineEdit_grid_save_name, 0, 3, 1, 1)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_grid_save)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 90, 361, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.buttonBox_grid_save = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_4)
        self.buttonBox_grid_save.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox_grid_save.setCenterButtons(True)
        self.buttonBox_grid_save.setObjectName("buttonBox_grid_save")
        self.verticalLayout_4.addWidget(self.buttonBox_grid_save)
        self.line_17 = QtWidgets.QFrame(self.groupBox_grid_save)
        self.line_17.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.groupBox_sys = QtWidgets.QGroupBox(self.Grid)
        self.groupBox_sys.setGeometry(QtCore.QRect(10, 10, 381, 151))
        self.groupBox_sys.setObjectName("groupBox_sys")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_sys)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 40, 361, 101))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_ndens = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_ndens.setObjectName("label_ndens")
        self.gridLayout_9.addWidget(self.label_ndens, 1, 0, 1, 1)
        self.lineEdit_temp = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_temp.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_temp.setPlaceholderText("")
        self.lineEdit_temp.setClearButtonEnabled(False)
        self.lineEdit_temp.setObjectName("lineEdit_temp")
        self.gridLayout_9.addWidget(self.lineEdit_temp, 0, 2, 1, 1)
        self.label_temp = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_temp.setObjectName("label_temp")
        self.gridLayout_9.addWidget(self.label_temp, 0, 0, 1, 1)
        self.lineEdit_nmdens = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_nmdens.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nmdens.setObjectName("lineEdit_nmdens")
        self.gridLayout_9.addWidget(self.lineEdit_nmdens, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 1, 1, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.groupBox_sys)
        self.line_9.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.groupBox_inter = QtWidgets.QGroupBox(self.Grid)
        self.groupBox_inter.setGeometry(QtCore.QRect(400, 240, 381, 311))
        self.groupBox_inter.setObjectName("groupBox_inter")
        self.line_10 = QtWidgets.QFrame(self.groupBox_inter)
        self.line_10.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_inter)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 40, 361, 261))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_mult = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_mult.setObjectName("label_mult")
        self.gridLayout_10.addWidget(self.label_mult, 0, 0, 1, 1)
        self.lineEdit_mult = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_mult.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_mult.setObjectName("lineEdit_mult")
        self.gridLayout_10.addWidget(self.lineEdit_mult, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 0, 1, 1, 1)
        self.lineEdit_die = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_die.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_die.setObjectName("lineEdit_die")
        self.gridLayout_10.addWidget(self.lineEdit_die, 1, 2, 1, 1)
        self.spinBox_terms = QtWidgets.QSpinBox(self.gridLayoutWidget_10)
        self.spinBox_terms.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_terms.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_terms.setMinimum(5)
        self.spinBox_terms.setMaximum(50)
        self.spinBox_terms.setProperty("value", 25)
        self.spinBox_terms.setObjectName("spinBox_terms")
        self.gridLayout_10.addWidget(self.spinBox_terms, 3, 2, 1, 1)
        self.label_die = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_die.setObjectName("label_die")
        self.gridLayout_10.addWidget(self.label_die, 1, 0, 1, 1)
        self.label_terms = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_terms.setObjectName("label_terms")
        self.gridLayout_10.addWidget(self.label_terms, 3, 0, 1, 1)
        self.gridLayout_method = QtWidgets.QGridLayout()
        self.gridLayout_method.setObjectName("gridLayout_method")
        self.radioButton_MPC = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_MPC.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_MPC.setChecked(True)
        self.radioButton_MPC.setObjectName("radioButton_MPC")
        self.gridLayout_method.addWidget(self.radioButton_MPC, 0, 0, 1, 1)
        self.radioButton_IPA = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_IPA.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_IPA.setObjectName("radioButton_IPA")
        self.gridLayout_method.addWidget(self.radioButton_IPA, 1, 0, 1, 1)
        self.radioButton_coul = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_coul.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_coul.setObjectName("radioButton_coul")
        self.gridLayout_method.addWidget(self.radioButton_coul, 3, 0, 1, 1)
        self.radioButton_Hybrid = QtWidgets.QRadioButton(self.gridLayoutWidget_10)
        self.radioButton_Hybrid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_Hybrid.setObjectName("radioButton_Hybrid")
        self.gridLayout_method.addWidget(self.radioButton_Hybrid, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_method, 2, 2, 1, 1)
        self.label_method = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.label_method.setObjectName("label_method")
        self.gridLayout_10.addWidget(self.label_method, 2, 0, 1, 1)
        self.groupBox_grid_desc = QtWidgets.QGroupBox(self.Grid)
        self.groupBox_grid_desc.setGeometry(QtCore.QRect(10, 620, 381, 131))
        self.groupBox_grid_desc.setObjectName("groupBox_grid_desc")
        self.line_18 = QtWidgets.QFrame(self.groupBox_grid_desc)
        self.line_18.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_grid_desc)
        self.gridLayoutWidget_12.setGeometry(QtCore.QRect(10, 40, 361, 86))
        self.gridLayoutWidget_12.setObjectName("gridLayoutWidget_12")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_12)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.textEdit_grid_desc = QtWidgets.QTextEdit(self.gridLayoutWidget_12)
        self.textEdit_grid_desc.setAcceptRichText(False)
        self.textEdit_grid_desc.setObjectName("textEdit_grid_desc")
        self.gridLayout_13.addWidget(self.textEdit_grid_desc, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Grid, "")
        self.Plasma_ini_tab = QtWidgets.QWidget()
        self.Plasma_ini_tab.setObjectName("Plasma_ini_tab")
        self.groupBox_plasmatime = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_plasmatime.setGeometry(QtCore.QRect(400, 10, 380, 220))
        self.groupBox_plasmatime.setObjectName("groupBox_plasmatime")
        self.line_6 = QtWidgets.QFrame(self.groupBox_plasmatime)
        self.line_6.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_plasmatime)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 40, 361, 171))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_plasmatimedelta = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_plasmatimedelta.setObjectName("label_plasmatimedelta")
        self.gridLayout_3.addWidget(self.label_plasmatimedelta, 0, 0, 1, 1)
        self.lineEdit_plasmatimedelta = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_plasmatimedelta.setText("")
        self.lineEdit_plasmatimedelta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_plasmatimedelta.setObjectName("lineEdit_plasmatimedelta")
        self.gridLayout_3.addWidget(self.lineEdit_plasmatimedelta, 0, 2, 1, 1)
        self.label_plasmatimesteps = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_plasmatimesteps.setObjectName("label_plasmatimesteps")
        self.gridLayout_3.addWidget(self.label_plasmatimesteps, 1, 0, 1, 1)
        self.lineEdit_plasmatimesteps = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_plasmatimesteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_plasmatimesteps.setObjectName("lineEdit_plasmatimesteps")
        self.gridLayout_3.addWidget(self.lineEdit_plasmatimesteps, 1, 2, 1, 1)
        self.label_plasmafreq = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_plasmafreq.setObjectName("label_plasmafreq")
        self.gridLayout_3.addWidget(self.label_plasmafreq, 2, 0, 1, 1)
        self.lineEdit_plasmafreq = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_plasmafreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_plasmafreq.setObjectName("lineEdit_plasmafreq")
        self.gridLayout_3.addWidget(self.lineEdit_plasmafreq, 2, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 1, 1, 1)
        self.groupBox_parameters = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_parameters.setEnabled(True)
        self.groupBox_parameters.setGeometry(QtCore.QRect(10, 10, 380, 261))
        self.groupBox_parameters.setObjectName("groupBox_parameters")
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_parameters)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 40, 361, 211))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_pfixed = QtWidgets.QCheckBox(self.gridLayoutWidget_8)
        self.checkBox_pfixed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_pfixed.setText("")
        self.checkBox_pfixed.setChecked(True)
        self.checkBox_pfixed.setTristate(False)
        self.checkBox_pfixed.setObjectName("checkBox_pfixed")
        self.gridLayout_8.addWidget(self.checkBox_pfixed, 0, 2, 1, 1)
        self.label_length = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_length.setObjectName("label_length")
        self.gridLayout_8.addWidget(self.label_length, 1, 0, 1, 1)
        self.label_temp_gas = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_temp_gas.setObjectName("label_temp_gas")
        self.gridLayout_8.addWidget(self.label_temp_gas, 2, 0, 1, 1)
        self.lineEdit_ng = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_ng.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_ng.setText("")
        self.lineEdit_ng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ng.setReadOnly(True)
        self.lineEdit_ng.setObjectName("lineEdit_ng")
        self.gridLayout_8.addWidget(self.lineEdit_ng, 4, 2, 1, 1)
        self.lineEdit_length = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_length.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_length.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_length.setObjectName("lineEdit_length")
        self.gridLayout_8.addWidget(self.lineEdit_length, 1, 2, 1, 1)
        self.lineEdit_pressure = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_pressure.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_pressure.setObjectName("lineEdit_pressure")
        self.gridLayout_8.addWidget(self.lineEdit_pressure, 3, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem6, 3, 1, 1, 1)
        self.label_pressure = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_pressure.setObjectName("label_pressure")
        self.gridLayout_8.addWidget(self.label_pressure, 3, 0, 1, 1)
        self.lineEdit_temp_gas = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_temp_gas.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_temp_gas.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_temp_gas.setPlaceholderText("")
        self.lineEdit_temp_gas.setClearButtonEnabled(False)
        self.lineEdit_temp_gas.setObjectName("lineEdit_temp_gas")
        self.gridLayout_8.addWidget(self.lineEdit_temp_gas, 2, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem8, 4, 1, 1, 1)
        self.label_ng = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_ng.setObjectName("label_ng")
        self.gridLayout_8.addWidget(self.label_ng, 4, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        self.label_pfixed = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.label_pfixed.setObjectName("label_pfixed")
        self.gridLayout_8.addWidget(self.label_pfixed, 0, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox_parameters)
        self.line_8.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.groupBox_plasma_save = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_plasma_save.setEnabled(True)
        self.groupBox_plasma_save.setGeometry(QtCore.QRect(400, 540, 380, 151))
        self.groupBox_plasma_save.setObjectName("groupBox_plasma_save")
        self.gridLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_plasma_save)
        self.gridLayoutWidget_18.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.gridLayoutWidget_18.setObjectName("gridLayoutWidget_18")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.gridLayoutWidget_18)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_plasma_save_name = QtWidgets.QLabel(self.gridLayoutWidget_18)
        self.label_plasma_save_name.setObjectName("label_plasma_save_name")
        self.gridLayout_18.addWidget(self.label_plasma_save_name, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem10, 0, 2, 1, 1)
        self.lineEdit_plasma_save_name = QtWidgets.QLineEdit(self.gridLayoutWidget_18)
        self.lineEdit_plasma_save_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_plasma_save_name.setObjectName("lineEdit_plasma_save_name")
        self.gridLayout_18.addWidget(self.lineEdit_plasma_save_name, 0, 3, 1, 1)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_plasma_save)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 90, 361, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.buttonBox_plasma_save = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_5)
        self.buttonBox_plasma_save.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox_plasma_save.setCenterButtons(True)
        self.buttonBox_plasma_save.setObjectName("buttonBox_plasma_save")
        self.verticalLayout_5.addWidget(self.buttonBox_plasma_save)
        self.line_19 = QtWidgets.QFrame(self.groupBox_plasma_save)
        self.line_19.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.groupBox_parameters_2 = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_parameters_2.setEnabled(True)
        self.groupBox_parameters_2.setGeometry(QtCore.QRect(400, 240, 380, 141))
        self.groupBox_parameters_2.setObjectName("groupBox_parameters_2")
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_parameters_2)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(10, 40, 361, 91))
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_ptol_2 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_ptol_2.setObjectName("label_ptol_2")
        self.gridLayout_11.addWidget(self.label_ptol_2, 1, 0, 1, 1)
        self.lineEdit_ipdens_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_ipdens_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ipdens_2.setObjectName("lineEdit_ipdens_2")
        self.gridLayout_11.addWidget(self.lineEdit_ipdens_2, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem11, 0, 1, 1, 1)
        self.label_ipdens_2 = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.label_ipdens_2.setObjectName("label_ipdens_2")
        self.gridLayout_11.addWidget(self.label_ipdens_2, 0, 0, 1, 1)
        self.lineEdit_ptol_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_11)
        self.lineEdit_ptol_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ptol_2.setObjectName("lineEdit_ptol_2")
        self.gridLayout_11.addWidget(self.lineEdit_ptol_2, 1, 2, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.groupBox_parameters_2)
        self.line_11.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.groupBox_electrons = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_electrons.setEnabled(True)
        self.groupBox_electrons.setGeometry(QtCore.QRect(10, 280, 380, 131))
        self.groupBox_electrons.setObjectName("groupBox_electrons")
        self.gridLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_electrons)
        self.gridLayoutWidget_13.setGeometry(QtCore.QRect(10, 40, 361, 91))
        self.gridLayoutWidget_13.setObjectName("gridLayoutWidget_13")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_13)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_ne = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_ne.setObjectName("label_ne")
        self.gridLayout_12.addWidget(self.label_ne, 1, 0, 1, 1)
        self.lineEdit_emean = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_emean.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_emean.setObjectName("lineEdit_emean")
        self.gridLayout_12.addWidget(self.lineEdit_emean, 0, 2, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_12.addItem(spacerItem12, 0, 1, 1, 1)
        self.label_emean = QtWidgets.QLabel(self.gridLayoutWidget_13)
        self.label_emean.setObjectName("label_emean")
        self.gridLayout_12.addWidget(self.label_emean, 0, 0, 1, 1)
        self.lineEdit_ne = QtWidgets.QLineEdit(self.gridLayoutWidget_13)
        self.lineEdit_ne.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ne.setReadOnly(False)
        self.lineEdit_ne.setObjectName("lineEdit_ne")
        self.gridLayout_12.addWidget(self.lineEdit_ne, 1, 2, 1, 1)
        self.line_12 = QtWidgets.QFrame(self.groupBox_electrons)
        self.line_12.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.groupBox_ions = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_ions.setEnabled(True)
        self.groupBox_ions.setGeometry(QtCore.QRect(10, 420, 380, 161))
        self.groupBox_ions.setObjectName("groupBox_ions")
        self.gridLayoutWidget_14 = QtWidgets.QWidget(self.groupBox_ions)
        self.gridLayoutWidget_14.setGeometry(QtCore.QRect(10, 40, 361, 121))
        self.gridLayoutWidget_14.setObjectName("gridLayoutWidget_14")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.gridLayoutWidget_14)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lineEdit_ni = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_ni.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ni.setReadOnly(False)
        self.lineEdit_ni.setObjectName("lineEdit_ni")
        self.gridLayout_14.addWidget(self.lineEdit_ni, 1, 2, 1, 1)
        self.label_ni = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_ni.setObjectName("label_ni")
        self.gridLayout_14.addWidget(self.label_ni, 1, 0, 1, 1)
        self.lineEdit_itemp = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_itemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_itemp.setObjectName("lineEdit_itemp")
        self.gridLayout_14.addWidget(self.lineEdit_itemp, 0, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem13, 0, 1, 1, 1)
        self.label_itemp = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_itemp.setObjectName("label_itemp")
        self.gridLayout_14.addWidget(self.label_itemp, 0, 0, 1, 1)
        self.label_imass = QtWidgets.QLabel(self.gridLayoutWidget_14)
        self.label_imass.setObjectName("label_imass")
        self.gridLayout_14.addWidget(self.label_imass, 2, 0, 1, 1)
        self.lineEdit_imass = QtWidgets.QLineEdit(self.gridLayoutWidget_14)
        self.lineEdit_imass.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_imass.setReadOnly(False)
        self.lineEdit_imass.setObjectName("lineEdit_imass")
        self.gridLayout_14.addWidget(self.lineEdit_imass, 2, 2, 1, 1)
        self.line_13 = QtWidgets.QFrame(self.groupBox_ions)
        self.line_13.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.groupBox_meta = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_meta.setEnabled(True)
        self.groupBox_meta.setGeometry(QtCore.QRect(10, 590, 380, 101))
        self.groupBox_meta.setObjectName("groupBox_meta")
        self.gridLayoutWidget_15 = QtWidgets.QWidget(self.groupBox_meta)
        self.gridLayoutWidget_15.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.gridLayoutWidget_15.setObjectName("gridLayoutWidget_15")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.gridLayoutWidget_15)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.lineEdit_nm = QtWidgets.QLineEdit(self.gridLayoutWidget_15)
        self.lineEdit_nm.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nm.setObjectName("lineEdit_nm")
        self.gridLayout_15.addWidget(self.lineEdit_nm, 0, 2, 1, 1)
        self.label_nm = QtWidgets.QLabel(self.gridLayoutWidget_15)
        self.label_nm.setObjectName("label_nm")
        self.gridLayout_15.addWidget(self.label_nm, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem14, 0, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.groupBox_meta)
        self.line_14.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.groupBox_plasma_desc = QtWidgets.QGroupBox(self.Plasma_ini_tab)
        self.groupBox_plasma_desc.setGeometry(QtCore.QRect(400, 400, 381, 131))
        self.groupBox_plasma_desc.setObjectName("groupBox_plasma_desc")
        self.line_20 = QtWidgets.QFrame(self.groupBox_plasma_desc)
        self.line_20.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_plasma_desc)
        self.gridLayoutWidget_16.setGeometry(QtCore.QRect(10, 40, 361, 86))
        self.gridLayoutWidget_16.setObjectName("gridLayoutWidget_16")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.gridLayoutWidget_16)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.textEdit_plasma_desc = QtWidgets.QTextEdit(self.gridLayoutWidget_16)
        self.textEdit_plasma_desc.setAcceptRichText(False)
        self.textEdit_plasma_desc.setObjectName("textEdit_plasma_desc")
        self.gridLayout_16.addWidget(self.textEdit_plasma_desc, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Plasma_ini_tab, "")
        self.Nano_ini_tab = QtWidgets.QWidget()
        self.Nano_ini_tab.setEnabled(True)
        self.Nano_ini_tab.setObjectName("Nano_ini_tab")
        self.groupBox_rates = QtWidgets.QGroupBox(self.Nano_ini_tab)
        self.groupBox_rates.setGeometry(QtCore.QRect(10, 200, 380, 261))
        self.groupBox_rates.setObjectName("groupBox_rates")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_rates)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 361, 211))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_nucleation = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_nucleation.setObjectName("label_nucleation")
        self.gridLayout_4.addWidget(self.label_nucleation, 0, 0, 1, 1)
        self.lineEdit_nucleation_rate = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_nucleation_rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nucleation_rate.setObjectName("lineEdit_nucleation_rate")
        self.gridLayout_4.addWidget(self.lineEdit_nucleation_rate, 0, 2, 1, 1)
        self.label_sgrowth = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_sgrowth.setObjectName("label_sgrowth")
        self.gridLayout_4.addWidget(self.label_sgrowth, 1, 0, 1, 1)
        self.lineEdit_sgrowth = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_sgrowth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_sgrowth.setObjectName("lineEdit_sgrowth")
        self.gridLayout_4.addWidget(self.lineEdit_sgrowth, 1, 2, 1, 1)
        self.checkBox_wsg = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_wsg.setText("")
        self.checkBox_wsg.setChecked(True)
        self.checkBox_wsg.setObjectName("checkBox_wsg")
        self.gridLayout_4.addWidget(self.checkBox_wsg, 1, 1, 1, 1)
        self.checkBox_wnu = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_wnu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_wnu.setText("")
        self.checkBox_wnu.setChecked(True)
        self.checkBox_wnu.setObjectName("checkBox_wnu")
        self.gridLayout_4.addWidget(self.checkBox_wnu, 0, 1, 1, 1)
        self.checkBox_wco = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_wco.setText("")
        self.checkBox_wco.setChecked(True)
        self.checkBox_wco.setObjectName("checkBox_wco")
        self.gridLayout_4.addWidget(self.checkBox_wco, 2, 1, 1, 1)
        self.label_wco = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_wco.setObjectName("label_wco")
        self.gridLayout_4.addWidget(self.label_wco, 2, 0, 1, 1)
        self.label_wch = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_wch.setObjectName("label_wch")
        self.gridLayout_4.addWidget(self.label_wch, 3, 0, 1, 1)
        self.checkBox_wch = QtWidgets.QCheckBox(self.gridLayoutWidget_3)
        self.checkBox_wch.setText("")
        self.checkBox_wch.setChecked(True)
        self.checkBox_wch.setObjectName("checkBox_wch")
        self.gridLayout_4.addWidget(self.checkBox_wch, 3, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_rates)
        self.line_3.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_time = QtWidgets.QGroupBox(self.Nano_ini_tab)
        self.groupBox_time.setGeometry(QtCore.QRect(10, 470, 380, 220))
        self.groupBox_time.setObjectName("groupBox_time")
        self.line_5 = QtWidgets.QFrame(self.groupBox_time)
        self.line_5.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_time)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 361, 171))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_ndeltat = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_ndeltat.setObjectName("label_ndeltat")
        self.gridLayout_2.addWidget(self.label_ndeltat, 0, 0, 1, 1)
        self.lineEdit_ndeltat = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_ndeltat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_ndeltat.setObjectName("lineEdit_ndeltat")
        self.gridLayout_2.addWidget(self.lineEdit_ndeltat, 0, 2, 1, 1)
        self.label_qdeltat = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_qdeltat.setObjectName("label_qdeltat")
        self.gridLayout_2.addWidget(self.label_qdeltat, 1, 0, 1, 1)
        self.lineEdit_qdeltat = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_qdeltat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_qdeltat.setObjectName("lineEdit_qdeltat")
        self.gridLayout_2.addWidget(self.lineEdit_qdeltat, 1, 2, 1, 1)
        self.label_timestop = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_timestop.setObjectName("label_timestop")
        self.gridLayout_2.addWidget(self.label_timestop, 2, 0, 1, 1)
        self.lineEdit_tstop = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_tstop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_tstop.setObjectName("lineEdit_tstop")
        self.gridLayout_2.addWidget(self.lineEdit_tstop, 2, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem15, 1, 1, 1, 1)
        self.groupBox_save = QtWidgets.QGroupBox(self.Nano_ini_tab)
        self.groupBox_save.setEnabled(True)
        self.groupBox_save.setGeometry(QtCore.QRect(400, 540, 380, 151))
        self.groupBox_save.setObjectName("groupBox_save")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_save)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 40, 361, 51))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_nano_save_name = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_nano_save_name.setObjectName("label_nano_save_name")
        self.gridLayout_6.addWidget(self.label_nano_save_name, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem16, 0, 2, 1, 1)
        self.lineEdit_nano_save_name = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_nano_save_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_nano_save_name.setObjectName("lineEdit_nano_save_name")
        self.gridLayout_6.addWidget(self.lineEdit_nano_save_name, 0, 3, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_save)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 361, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonBox_nano_save = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget_2)
        self.buttonBox_nano_save.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Reset|QtWidgets.QDialogButtonBox.Save|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox_nano_save.setCenterButtons(True)
        self.buttonBox_nano_save.setObjectName("buttonBox_nano_save")
        self.verticalLayout_2.addWidget(self.buttonBox_nano_save)
        self.line_2 = QtWidgets.QFrame(self.groupBox_save)
        self.line_2.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_ndensity = QtWidgets.QGroupBox(self.Nano_ini_tab)
        self.groupBox_ndensity.setEnabled(True)
        self.groupBox_ndensity.setGeometry(QtCore.QRect(400, 10, 380, 381))
        self.groupBox_ndensity.setObjectName("groupBox_ndensity")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_ndensity)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 40, 361, 331))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.spinBox_width = QtWidgets.QSpinBox(self.gridLayoutWidget_7)
        self.spinBox_width.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_width.setMinimum(0)
        self.spinBox_width.setMaximum(250)
        self.spinBox_width.setSingleStep(1)
        self.spinBox_width.setProperty("value", 10)
        self.spinBox_width.setObjectName("spinBox_width")
        self.gridLayout_7.addWidget(self.spinBox_width, 4, 2, 1, 1)
        self.spinBox_peakpos = QtWidgets.QSpinBox(self.gridLayoutWidget_7)
        self.spinBox_peakpos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_peakpos.setMinimum(0)
        self.spinBox_peakpos.setMaximum(250)
        self.spinBox_peakpos.setSingleStep(1)
        self.spinBox_peakpos.setProperty("value", 0)
        self.spinBox_peakpos.setObjectName("spinBox_peakpos")
        self.gridLayout_7.addWidget(self.spinBox_peakpos, 2, 2, 1, 1)
        self.label_qtol = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_qtol.setObjectName("label_qtol")
        self.gridLayout_7.addWidget(self.label_qtol, 5, 0, 1, 1)
        self.label_indens = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_indens.setObjectName("label_indens")
        self.gridLayout_7.addWidget(self.label_indens, 0, 0, 1, 1)
        self.lineEdit_qtol = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_qtol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_qtol.setObjectName("lineEdit_qtol")
        self.gridLayout_7.addWidget(self.lineEdit_qtol, 5, 2, 1, 1)
        self.lineEdit_indens = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_indens.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_indens.setObjectName("lineEdit_indens")
        self.gridLayout_7.addWidget(self.lineEdit_indens, 0, 2, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem17, 0, 1, 1, 1)
        self.label_distribution = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_distribution.setObjectName("label_distribution")
        self.gridLayout_7.addWidget(self.label_distribution, 1, 0, 1, 1)
        self.label_width = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_width.setObjectName("label_width")
        self.gridLayout_7.addWidget(self.label_width, 4, 0, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.radioButton_delta = QtWidgets.QRadioButton(self.gridLayoutWidget_7)
        self.radioButton_delta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_delta.setChecked(True)
        self.radioButton_delta.setObjectName("radioButton_delta")
        self.gridLayout_21.addWidget(self.radioButton_delta, 0, 0, 1, 1)
        self.radioButton_step = QtWidgets.QRadioButton(self.gridLayoutWidget_7)
        self.radioButton_step.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_step.setObjectName("radioButton_step")
        self.gridLayout_21.addWidget(self.radioButton_step, 1, 0, 1, 1)
        self.radioButton_gaussian = QtWidgets.QRadioButton(self.gridLayoutWidget_7)
        self.radioButton_gaussian.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.radioButton_gaussian.setObjectName("radioButton_gaussian")
        self.gridLayout_21.addWidget(self.radioButton_gaussian, 2, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_21, 1, 2, 1, 1)
        self.label_peakpos = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_peakpos.setObjectName("label_peakpos")
        self.gridLayout_7.addWidget(self.label_peakpos, 2, 0, 1, 1)
        self.label_radius = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_radius.setObjectName("label_radius")
        self.gridLayout_7.addWidget(self.label_radius, 3, 0, 1, 1)
        self.lineEdit_radius = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_radius.setText("")
        self.lineEdit_radius.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_radius.setReadOnly(True)
        self.lineEdit_radius.setObjectName("lineEdit_radius")
        self.gridLayout_7.addWidget(self.lineEdit_radius, 3, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.groupBox_ndensity)
        self.line_7.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.groupBox_nano_desc = QtWidgets.QGroupBox(self.Nano_ini_tab)
        self.groupBox_nano_desc.setGeometry(QtCore.QRect(400, 400, 381, 131))
        self.groupBox_nano_desc.setObjectName("groupBox_nano_desc")
        self.line_21 = QtWidgets.QFrame(self.groupBox_nano_desc)
        self.line_21.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_nano_desc)
        self.gridLayoutWidget_19.setGeometry(QtCore.QRect(10, 40, 361, 86))
        self.gridLayoutWidget_19.setObjectName("gridLayoutWidget_19")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_19)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.textEdit_nano_desc = QtWidgets.QTextEdit(self.gridLayoutWidget_19)
        self.textEdit_nano_desc.setAcceptRichText(False)
        self.textEdit_nano_desc.setObjectName("textEdit_nano_desc")
        self.gridLayout_19.addWidget(self.textEdit_nano_desc, 0, 0, 1, 1)
        self.groupBox_nanoparticles = QtWidgets.QGroupBox(self.Nano_ini_tab)
        self.groupBox_nanoparticles.setGeometry(QtCore.QRect(10, 10, 381, 181))
        self.groupBox_nanoparticles.setObjectName("groupBox_nanoparticles")
        self.gridLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_nanoparticles)
        self.gridLayoutWidget_20.setGeometry(QtCore.QRect(10, 40, 361, 131))
        self.gridLayoutWidget_20.setObjectName("gridLayoutWidget_20")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.gridLayoutWidget_20)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_acc = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_acc.setObjectName("label_acc")
        self.gridLayout_20.addWidget(self.label_acc, 2, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_20.addItem(spacerItem18, 2, 1, 1, 1)
        self.lineEdit_acc = QtWidgets.QLineEdit(self.gridLayoutWidget_20)
        self.lineEdit_acc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_acc.setObjectName("lineEdit_acc")
        self.gridLayout_20.addWidget(self.lineEdit_acc, 2, 2, 1, 1)
        self.lineEdit_eaffinity = QtWidgets.QLineEdit(self.gridLayoutWidget_20)
        self.lineEdit_eaffinity.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit_eaffinity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_eaffinity.setPlaceholderText("")
        self.lineEdit_eaffinity.setClearButtonEnabled(False)
        self.lineEdit_eaffinity.setObjectName("lineEdit_eaffinity")
        self.gridLayout_20.addWidget(self.lineEdit_eaffinity, 1, 2, 1, 1)
        self.label_eaffinity = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_eaffinity.setObjectName("label_eaffinity")
        self.gridLayout_20.addWidget(self.label_eaffinity, 1, 0, 1, 1)
        self.label_tunnel = QtWidgets.QLabel(self.gridLayoutWidget_20)
        self.label_tunnel.setObjectName("label_tunnel")
        self.gridLayout_20.addWidget(self.label_tunnel, 0, 0, 1, 1)
        self.checkBox_tunnel = QtWidgets.QCheckBox(self.gridLayoutWidget_20)
        self.checkBox_tunnel.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_tunnel.setText("")
        self.checkBox_tunnel.setChecked(True)
        self.checkBox_tunnel.setObjectName("checkBox_tunnel")
        self.gridLayout_20.addWidget(self.checkBox_tunnel, 0, 2, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.groupBox_nanoparticles)
        self.line_15.setGeometry(QtCore.QRect(10, 20, 360, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.tabWidget.addTab(self.Nano_ini_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_plasma = QtWidgets.QAction(MainWindow)
        self.actionOpen_plasma.setObjectName("actionOpen_plasma")
        self.actionOpen_Nano = QtWidgets.QAction(MainWindow)
        self.actionOpen_Nano.setObjectName("actionOpen_Nano")
        self.menuFile.addAction(self.actionOpen_plasma)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_Nano)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_temp, self.lineEdit_nmdens)
        MainWindow.setTabOrder(self.lineEdit_nmdens, self.lineEdit_minrad)
        MainWindow.setTabOrder(self.lineEdit_minrad, self.lineEdit_minvol)
        MainWindow.setTabOrder(self.lineEdit_minvol, self.lineEdit_maxrad)
        MainWindow.setTabOrder(self.lineEdit_maxrad, self.lineEdit_maxvol)
        MainWindow.setTabOrder(self.lineEdit_maxvol, self.spinBox_vsecs)
        MainWindow.setTabOrder(self.spinBox_vsecs, self.lineEdit_base)
        MainWindow.setTabOrder(self.lineEdit_base, self.lineEdit_power)
        MainWindow.setTabOrder(self.lineEdit_power, self.spinBox_maxneg)
        MainWindow.setTabOrder(self.spinBox_maxneg, self.spinBox_maxpos)
        MainWindow.setTabOrder(self.spinBox_maxpos, self.lineEdit_qsecs)
        MainWindow.setTabOrder(self.lineEdit_qsecs, self.lineEdit_mult)
        MainWindow.setTabOrder(self.lineEdit_mult, self.lineEdit_die)
        MainWindow.setTabOrder(self.lineEdit_die, self.radioButton_MPC)
        MainWindow.setTabOrder(self.radioButton_MPC, self.radioButton_IPA)
        MainWindow.setTabOrder(self.radioButton_IPA, self.radioButton_coul)
        MainWindow.setTabOrder(self.radioButton_coul, self.spinBox_terms)
        MainWindow.setTabOrder(self.spinBox_terms, self.lineEdit_grid_save_name)
        MainWindow.setTabOrder(self.lineEdit_grid_save_name, self.checkBox_pfixed)
        MainWindow.setTabOrder(self.checkBox_pfixed, self.lineEdit_length)
        MainWindow.setTabOrder(self.lineEdit_length, self.lineEdit_temp_gas)
        MainWindow.setTabOrder(self.lineEdit_temp_gas, self.lineEdit_pressure)
        MainWindow.setTabOrder(self.lineEdit_pressure, self.lineEdit_ng)
        MainWindow.setTabOrder(self.lineEdit_ng, self.lineEdit_emean)
        MainWindow.setTabOrder(self.lineEdit_emean, self.lineEdit_ne)
        MainWindow.setTabOrder(self.lineEdit_ne, self.lineEdit_itemp)
        MainWindow.setTabOrder(self.lineEdit_itemp, self.lineEdit_ni)
        MainWindow.setTabOrder(self.lineEdit_ni, self.lineEdit_nm)
        MainWindow.setTabOrder(self.lineEdit_nm, self.lineEdit_plasmatimedelta)
        MainWindow.setTabOrder(self.lineEdit_plasmatimedelta, self.lineEdit_plasmatimesteps)
        MainWindow.setTabOrder(self.lineEdit_plasmatimesteps, self.lineEdit_plasmafreq)
        MainWindow.setTabOrder(self.lineEdit_plasmafreq, self.lineEdit_ipdens_2)
        MainWindow.setTabOrder(self.lineEdit_ipdens_2, self.lineEdit_ptol_2)
        MainWindow.setTabOrder(self.lineEdit_ptol_2, self.lineEdit_plasma_save_name)
        MainWindow.setTabOrder(self.lineEdit_plasma_save_name, self.checkBox_tunnel)
        MainWindow.setTabOrder(self.checkBox_tunnel, self.lineEdit_eaffinity)
        MainWindow.setTabOrder(self.lineEdit_eaffinity, self.lineEdit_acc)
        MainWindow.setTabOrder(self.lineEdit_acc, self.checkBox_wnu)
        MainWindow.setTabOrder(self.checkBox_wnu, self.lineEdit_nucleation_rate)
        MainWindow.setTabOrder(self.lineEdit_nucleation_rate, self.checkBox_wsg)
        MainWindow.setTabOrder(self.checkBox_wsg, self.lineEdit_sgrowth)
        MainWindow.setTabOrder(self.lineEdit_sgrowth, self.checkBox_wco)
        MainWindow.setTabOrder(self.checkBox_wco, self.checkBox_wch)
        MainWindow.setTabOrder(self.checkBox_wch, self.lineEdit_ndeltat)
        MainWindow.setTabOrder(self.lineEdit_ndeltat, self.lineEdit_qdeltat)
        MainWindow.setTabOrder(self.lineEdit_qdeltat, self.lineEdit_tstop)
        MainWindow.setTabOrder(self.lineEdit_tstop, self.lineEdit_indens)
        MainWindow.setTabOrder(self.lineEdit_indens, self.lineEdit_qtol)
        MainWindow.setTabOrder(self.lineEdit_qtol, self.lineEdit_nano_save_name)
        MainWindow.setTabOrder(self.lineEdit_nano_save_name, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.textEdit_grid_desc)
        MainWindow.setTabOrder(self.textEdit_grid_desc, self.textEdit_plasma_desc)
        MainWindow.setTabOrder(self.textEdit_plasma_desc, self.textEdit_nano_desc)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "nDust"))
        self.groupBox_volumes.setTitle(_translate("MainWindow", "Volumes"))
        self.lineEdit_maxrad.setToolTip(_translate("MainWindow", "Maximum mean radius"))
        self.lineEdit_minvol.setToolTip(_translate("MainWindow", "Minimum volume at interface"))
        self.label_numvsecs.setText(_translate("MainWindow", "Number of sections"))
        self.label_base.setText(_translate("MainWindow", "Base"))
        self.label_maxrad.setToolTip(_translate("MainWindow", "Maximum mean radius"))
        self.label_maxrad.setText(_translate("MainWindow", "Maximum radius (nm)"))
        self.lineEdit_maxvol.setToolTip(_translate("MainWindow", "Maximum volume at interface"))
        self.label_minvol.setToolTip(_translate("MainWindow", "Minimum volume at interface"))
        self.label_minvol.setText(_translate("MainWindow", "Minimum volume (m³)"))
        self.lineEdit_base.setText(_translate("MainWindow", "1.5"))
        self.label_maxvol.setToolTip(_translate("MainWindow", "Maximum volume at interface"))
        self.label_maxvol.setText(_translate("MainWindow", "Maximum volume(m³)"))
        self.label_power.setText(_translate("MainWindow", "Power"))
        self.lineEdit_minrad.setToolTip(_translate("MainWindow", "Minimum mean radius"))
        self.lineEdit_minrad.setText(_translate("MainWindow", "0.375"))
        self.lineEdit_power.setText(_translate("MainWindow", "1"))
        self.label_minrad.setToolTip(_translate("MainWindow", "Minimum mean radius"))
        self.label_minrad.setText(_translate("MainWindow", "Minimum radius (nm)"))
        self.label_linear.setText(_translate("MainWindow", "Linear sections"))
        self.label_special.setText(_translate("MainWindow", "Special sections"))
        self.label_special_2.setText(_translate("MainWindow", "Small versus"))
        self.label_special_3.setText(_translate("MainWindow", "Big versus"))
        self.groupBox_charges.setTitle(_translate("MainWindow", "Charges"))
        self.label_maxneg.setText(_translate("MainWindow", "Maximum negative"))
        self.label_maxpos.setText(_translate("MainWindow", "Maximum positive   "))
        self.label_qsecs.setText(_translate("MainWindow", "Number of sections"))
        self.groupBox_grid_save.setTitle(_translate("MainWindow", "Save"))
        self.label_grid_save_name.setText(_translate("MainWindow", "Grid filename"))
        self.lineEdit_grid_save_name.setText(_translate("MainWindow", "grid.h5"))
        self.groupBox_sys.setTitle(_translate("MainWindow", "System"))
        self.label_ndens.setText(_translate("MainWindow", "Nanoparticle density"))
        self.lineEdit_temp.setToolTip(_translate("MainWindow", "Nanoparticle temperature"))
        self.lineEdit_temp.setText(_translate("MainWindow", "300.0"))
        self.label_temp.setText(_translate("MainWindow", "Temperature"))
        self.lineEdit_nmdens.setToolTip(_translate("MainWindow", "Nanoparticle mass density"))
        self.lineEdit_nmdens.setText(_translate("MainWindow", "2329.0"))
        self.groupBox_inter.setTitle(_translate("MainWindow", "Electrostatic interaction"))
        self.label_mult.setText(_translate("MainWindow", "Multiplier"))
        self.lineEdit_mult.setText(_translate("MainWindow", "1.0"))
        self.lineEdit_die.setText(_translate("MainWindow", "11.68"))
        self.label_die.setText(_translate("MainWindow", "Dielectric constant"))
        self.label_terms.setText(_translate("MainWindow", "Terms"))
        self.radioButton_MPC.setText(_translate("MainWindow", "MPC"))
        self.radioButton_IPA.setText(_translate("MainWindow", "IPA"))
        self.radioButton_coul.setText(_translate("MainWindow", "Co&ulomb"))
        self.radioButton_Hybrid.setText(_translate("MainWindow", "Hybrid"))
        self.label_method.setText(_translate("MainWindow", "Method"))
        self.groupBox_grid_desc.setTitle(_translate("MainWindow", "Description"))
        self.textEdit_grid_desc.setPlaceholderText(_translate("MainWindow", "Enter here a description for this grid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Grid), _translate("MainWindow", "Grid"))
        self.groupBox_plasmatime.setTitle(_translate("MainWindow", "Time"))
        self.label_plasmatimedelta.setText(_translate("MainWindow", "Time delta (s)"))
        self.label_plasmatimesteps.setText(_translate("MainWindow", "Steps by period"))
        self.lineEdit_plasmatimesteps.setText(_translate("MainWindow", "5000"))
        self.label_plasmafreq.setText(_translate("MainWindow", "Frequency"))
        self.lineEdit_plasmafreq.setText(_translate("MainWindow", "13.56E6"))
        self.groupBox_parameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label_length.setText(_translate("MainWindow", "Length (m)"))
        self.label_temp_gas.setText(_translate("MainWindow", "Temperature"))
        self.lineEdit_length.setText(_translate("MainWindow", "0.03"))
        self.lineEdit_pressure.setText(_translate("MainWindow", "133.32237"))
        self.label_pressure.setText(_translate("MainWindow", "Pressure (Pa)"))
        self.lineEdit_temp_gas.setToolTip(_translate("MainWindow", "Nanoparticle temperature"))
        self.lineEdit_temp_gas.setText(_translate("MainWindow", "300.0"))
        self.label_ng.setText(_translate("MainWindow", "Neutral gas density (1/m³)"))
        self.label_pfixed.setText(_translate("MainWindow", "Fixed plasma parameters"))
        self.groupBox_plasma_save.setTitle(_translate("MainWindow", "Save"))
        self.label_plasma_save_name.setText(_translate("MainWindow", "Plasma filename"))
        self.lineEdit_plasma_save_name.setText(_translate("MainWindow", "plasma.h5"))
        self.groupBox_parameters_2.setTitle(_translate("MainWindow", "Parameters"))
        self.label_ptol_2.setText(_translate("MainWindow", "%Rel. error plasma profiles"))
        self.lineEdit_ipdens_2.setText(_translate("MainWindow", "5.0E13"))
        self.label_ipdens_2.setText(_translate("MainWindow", "Initial density"))
        self.lineEdit_ptol_2.setText(_translate("MainWindow", "0.05"))
        self.groupBox_electrons.setTitle(_translate("MainWindow", "Electrons"))
        self.label_ne.setText(_translate("MainWindow", "Electron density (1/m³)"))
        self.lineEdit_emean.setText(_translate("MainWindow", "5.0"))
        self.label_emean.setText(_translate("MainWindow", "Energy (eV)"))
        self.lineEdit_ne.setText(_translate("MainWindow", "1e15"))
        self.groupBox_ions.setTitle(_translate("MainWindow", "Ions"))
        self.lineEdit_ni.setText(_translate("MainWindow", "1e15"))
        self.label_ni.setText(_translate("MainWindow", "Ion density (1/m³)"))
        self.lineEdit_itemp.setText(_translate("MainWindow", "300.0"))
        self.label_itemp.setText(_translate("MainWindow", "Ion temperature (K)"))
        self.label_imass.setText(_translate("MainWindow", "Ion mass (Kg)"))
        self.lineEdit_imass.setText(_translate("MainWindow", "6.63352e-26"))
        self.groupBox_meta.setTitle(_translate("MainWindow", "Metastables"))
        self.lineEdit_nm.setText(_translate("MainWindow", "1e16"))
        self.label_nm.setText(_translate("MainWindow", "Metastable density (1/m³)"))
        self.groupBox_plasma_desc.setTitle(_translate("MainWindow", "Description"))
        self.textEdit_plasma_desc.setPlaceholderText(_translate("MainWindow", "Enter here a description for the set of plasma parameters"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Plasma_ini_tab), _translate("MainWindow", "Plasma"))
        self.groupBox_rates.setTitle(_translate("MainWindow", "Rates"))
        self.label_nucleation.setText(_translate("MainWindow", "Nucleation rate (1/m³s)"))
        self.lineEdit_nucleation_rate.setText(_translate("MainWindow", "1.0E18"))
        self.label_sgrowth.setText(_translate("MainWindow", "Linear surface growth (nm/s)   "))
        self.lineEdit_sgrowth.setText(_translate("MainWindow", "12.0E-9"))
        self.label_wco.setText(_translate("MainWindow", "Coagulation"))
        self.label_wch.setText(_translate("MainWindow", "Charging"))
        self.groupBox_time.setTitle(_translate("MainWindow", "Time"))
        self.label_ndeltat.setText(_translate("MainWindow", "Growth delta time (s)"))
        self.lineEdit_ndeltat.setText(_translate("MainWindow", "1e-7"))
        self.label_qdeltat.setText(_translate("MainWindow", "Charging delta time (s)"))
        self.lineEdit_qdeltat.setText(_translate("MainWindow", "1e-10"))
        self.label_timestop.setText(_translate("MainWindow", "Time stop (s)"))
        self.lineEdit_tstop.setText(_translate("MainWindow", "0.02"))
        self.groupBox_save.setTitle(_translate("MainWindow", "Save"))
        self.label_nano_save_name.setText(_translate("MainWindow", "Nano filename"))
        self.lineEdit_nano_save_name.setText(_translate("MainWindow", "nano.h5"))
        self.groupBox_ndensity.setTitle(_translate("MainWindow", "Density"))
        self.label_qtol.setText(_translate("MainWindow", "%Rel. error total part charge"))
        self.label_indens.setText(_translate("MainWindow", "Initial nanoparticle density"))
        self.lineEdit_qtol.setText(_translate("MainWindow", "0.01"))
        self.lineEdit_indens.setText(_translate("MainWindow", "1.0E15"))
        self.label_distribution.setText(_translate("MainWindow", "Distribution type"))
        self.label_width.setText(_translate("MainWindow", "Width"))
        self.radioButton_delta.setText(_translate("MainWindow", "&Delta"))
        self.radioButton_step.setText(_translate("MainWindow", "Step"))
        self.radioButton_gaussian.setText(_translate("MainWindow", "Ga&ussian"))
        self.label_peakpos.setText(_translate("MainWindow", "Peak in section"))
        self.label_radius.setToolTip(_translate("MainWindow", "Minimum mean radius"))
        self.label_radius.setText(_translate("MainWindow", "Radius (nm)"))
        self.lineEdit_radius.setToolTip(_translate("MainWindow", "Minimum mean radius"))
        self.groupBox_nano_desc.setTitle(_translate("MainWindow", "Description"))
        self.textEdit_nano_desc.setPlaceholderText(_translate("MainWindow", "Enter here a description for this grid"))
        self.groupBox_nanoparticles.setTitle(_translate("MainWindow", "Nanoparticles"))
        self.label_acc.setText(_translate("MainWindow", "Accomodation factor"))
        self.lineEdit_acc.setToolTip(_translate("MainWindow", "Nanoparticle mass density"))
        self.lineEdit_acc.setText(_translate("MainWindow", "0.9"))
        self.lineEdit_eaffinity.setToolTip(_translate("MainWindow", "Nanoparticle temperature"))
        self.lineEdit_eaffinity.setText(_translate("MainWindow", "4.05"))
        self.label_eaffinity.setText(_translate("MainWindow", "Electron affinity (eV)"))
        self.label_tunnel.setText(_translate("MainWindow", "Tunnel current"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Nano_ini_tab), _translate("MainWindow", "Nano"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.actionOpen_plasma.setText(_translate("MainWindow", "&Open Plasma"))
        self.actionOpen_Nano.setText(_translate("MainWindow", "Open &Nano"))

